### ISSUE TITLE
Translucency of the settings is confusing

### ISSUE THREAD

**Issue by dictvm** [leifniem/didit#2]
The translucency is problematic because it's not obvious which options are clickable. 

The text "Want to start over" looks like it resides behind the settings-overlay because the font is being rendered in dark grey which looks like it used to be white with a black translucent overlay. Using the light theme leads to the same effect with opposite colors.

Suggestion: Get rid of the translucency and sacrifice fancyness for better usability.

**Comment by leifniem** [comment]
approved and about to be updated!

**Comment by leifniem** [comment]
updated the zip for the 0.1 alpha
